name: Deploy to Cloud Run

on:
  push:
    branches: ["main"]         # ← main にマージされたら発火

permissions:
  id-token: write             # OIDC トークン必須
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authentication
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker asia-northeast1-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t asia-northeast1-docker.pkg.dev/buoyant-airport-162001/github-actions-test/flask-supu-app .

      - name: Push Docker image
        run: |
          docker push asia-northeast1-docker.pkg.dev/buoyant-airport-162001/github-actions-test/flask-supu-app

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: flask-supu-app
          region: asia-northeast1
          image: asia-northeast1-docker.pkg.dev/buoyant-airport-162001/github-actions-test/flask-supu-app
          
